### PR TITLE
Remove .DS_Store

### PR DESCRIPTION
**Pull request by yous**

### CODE REVIEW

**Comment by frdmn** [comment]
Just raised another PR (#288), which also includes an .gitignore to prevent further indexing of unwanted meta stuff.

**Comment by yous** [comment]
@frdmn You can close this via your PR.

**Comment by frdmn** [comment]
@yous I think I don't have the permissions to close another persons PR. :/

**Comment by yous** [comment]
@frdmn You can state `Fix #254` in the description of your PR to close this PR automatically when your PR is merged. :smile:

**Comment by frdmn** [comment]
Ah! Thanks for this :+1:

**Pull request closed without merging**
